
jobs:
- job: 'Test'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: pip install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      python -m pip install flake8
      flake8 .
    displayName: 'Run lint tests'
    continueOnError: true

  - script: |
      pip install pytest pytest-cov pytest-azurepipelines
      pytest . --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
    displayName: 'Test with pytest'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

# - job: 'Publish'
#   pool:
#     vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

#   steps:
#   # Install python distributions like wheel, twine etc
#   - script: pip install wheel twine

#   # Build the python distribution from source
#   - script: python setup.py bdist_wheel

#   # Use command line script to 'twine upload', use -r to pass the repository name and --config-file to pass the environment variable set by the authenticate task.
#   - script: python -m twine upload --config-file $(PYPIRC_PATH) dist/*.whl
